apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: 15
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 75
      type: Resource
